### ISSUE TITLE
Angular 9 bug

### ISSUE THREAD

**Issue by abenhamo** [gmerabishvili/angular-ng-autocomplete#74]
Hello,
When I updated my angular version to 9 I'm having this error:
```
ERROR in Failed to compile entry-point angular-ng-autocomplete (es2015 as esm2015) due to compilation errors:
node_modules/angular-ng-autocomplete/fesm2015/angular-ng-autocomplete.js:949:20 - error NG1006: Cannot combine @Input decorators with query decorators
```

Thank you

**Comment by gmerabishvili** [comment]
@abenhamo Did you fix it?

**Comment by abenhamo** [comment]
@gmerabishvili not yet, I downgraded to Angular8

**Comment by gmerabishvili** [comment]
@abenhamo Ok, I'll update the library to Angular 9 soon.

**Comment by abenhamo** [comment]
@gmerabishvili  Thank you

**Comment by gmerabishvili** [comment]
Hello, The library is upgraded to Angular 9 : ) You can install latest 2.0.1 version. Thank you!
